modLoader="javafml"
loaderVersion="[47,)"
license="MIT (CC BY-NC-SA 4.0 for some Assets)"
issueTrackerURL="https://github.com/quiqueck/bclib/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
description="A library for BetterX team mods"
authors="Quiqueck, paulevs, Bulldog83"
displayURL="https://modrinth.com/mod/bclib"
logoFile="assets/bclib/icon.png"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="wunderlib"
mandatory=true
versionRange="[${wunderlib_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="emi"
mandatory=false
versionRange="[1.0,)"
ordering="NONE"
side="CLIENT"

[[mixins]]
config="together.mixins.common.json"

[[mixins]]
config="together.mixins.client.json"

[[mixins]]
config="ui.mixins.client.json"

[[mixins]]
config="bclib.mixins.common.json"

[[mixins]]
config="bclib.mixins.client.json"
